import Augmentor
import os
import shutil
from PIL import Image
import numpy as np

pathA = 'Data/A'
pathB = 'Data/B'

p = Augmentor.Pipeline(pathA)
# Point to a directory containing ground truth data.
# Images with the same file names will be added as ground truth data
# and augmented in parallel to the original data.
p.ground_truth(pathB)

# Add operations to the pipeline:
p.rotate90(probability=0.25)
p.rotate270(probability=0.25)
p.flip_left_right(probability=0.25)
p.flip_top_bottom(probability=0.25)

IMAGE_COUNT = 300

p.sample(IMAGE_COUNT)

newPathA = "/Users/Amy/Documents/GitHub/AI-Queens/Data/Augmented/A/"
newPathB = "/Users/Amy/Documents/GitHub/AI-Queens/Data/Augmented/B/"
combinedPath = "/Users/Amy/Documents/GitHub/AI-Queens/Data/Augmented/Combined/"

# Iterate over the files generated by the Augmentor pipeline and copy them to a new directory
# The empty destination directory needs to exist before running this cell

# This is the default location that Augmentor will have saved the sampled images
os.chdir(pathA + '/output')

A_files = []
B_files = []

for filename in os.listdir('.'):
  if 'A_original' in filename:
      # guid will include the .png suffix
      guid = filename[-16:]
      A_files.append(guid)
      # shutil.copyfile(src, dst, *, follow_symlinks=True)
      dst = newPathA + guid
      shutil.copyfile(filename, dst)
  if '_groundtruth_' in filename:
      # guid will include the .png suffix
      guid = filename[-16:]
      B_files.append(guid)
      # shutil.copyfile(src, dst, *, follow_symlinks=True)
      dst = newPathB + guid
      shutil.copyfile(filename, dst)

print("A Filenames Found: ", A_files)
print("B Filenames Found: ", B_files)

# Combine Augmented Images into the pair format that Pix2Pix expects
os.chdir(newPathA)
for filename in os.listdir('.'):
  im1 = Image.open(filename)
  im2 = Image.open(newPathB + filename)

  # Combine images horizontally using PIL
  dst = Image.new('RGB', (512, 256))
  dst.paste(im1, (0, 0))
  dst.paste(im2, (im1.width, 0))
  dst.save(combinedPath + filename)

# Train/Test Split
# Takes the files in '../Augmented/Combined/' and randomly splits them into './Combined/Train' and './Combined/Test' directories
os.chdir(combinedPath)
test_dir = combinedPath + 'Test/'
train_dir = combinedPath + 'Train/'

files = os.listdir(combinedPath)
ratio = 0.15

for f in files:
    if '.png' in f:
      if np.random.rand(1) < ratio:
          shutil.copyfile(combinedPath + f, test_dir + f)
      else:
          shutil.copyfile(combinedPath + f, train_dir + f)

# Check that files exist in new location:

# os.chdir(pathA+ '/output')
os.chdir(train_dir)
print(len([name for name in os.listdir('.') if os.path.isfile(name)]))